//! Custom D2D effect-graph for WinRT Composition: `IGraphicsEffectD2D1Interop`
//! via a generic `D2dEffectNode` (Win2D's effect classes are UWP-only).
//! Builds `backdrop → GaussianBlur(σ) → Saturation → Contrast`.

#![allow(
    unsafe_code,
    reason = "FFI boundary; `#[implement]` COM vtable and PropertyValue boxing."
)]
#![allow(
    trivial_casts,
    reason = "from vtable casts generated by the windows-rs `#[implement]` macro."
)]

use std::cell::RefCell;

use windows::Foundation::{IPropertyValue, PropertyValue};
use windows::Graphics::Effects::{
    IGraphicsEffect, IGraphicsEffectSource, IGraphicsEffectSource_Impl,
};
use windows::UI::Composition::{CompositionBrush, CompositionEffectSourceParameter, Compositor};
use windows::Win32::Graphics::Direct2D::Common::D2D1_BORDER_MODE_HARD;
use windows::Win32::Graphics::Direct2D::{
    CLSID_D2D1Contrast, CLSID_D2D1GaussianBlur, CLSID_D2D1Saturation,
    D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED,
};
use windows::Win32::System::WinRT::Graphics::Direct2D::{
    GRAPHICS_EFFECT_PROPERTY_MAPPING, GRAPHICS_EFFECT_PROPERTY_MAPPING_DIRECT,
    IGraphicsEffectD2D1Interop, IGraphicsEffectD2D1Interop_Impl,
};
use windows::core::{Error, GUID, HSTRING, Interface, PCWSTR, Result as WinResult, implement};

use crate::error::{Result, map_hr};

/// Source param name; also plugs the backdrop via `SetSourceParameter`.
const SOURCE_NAME: &str = "source";

/// Default `Saturation`, `[0, 1]` (0.5 = identity).
const BLUR_SATURATION: f32 = 0.70;
/// Default `Contrast`, `[-1, 1]` (0 = identity).
const BLUR_CONTRAST: f32 = 0.15;

/// Generic D2D effect node: one CLSID, a property list, one source.
/// Properties must be boxed in the count/order/type of the CLSID's registered
/// schema or `CreateEffectFactory` returns `E_INVALIDARG`.
#[implement(IGraphicsEffect, IGraphicsEffectSource, IGraphicsEffectD2D1Interop)]
struct D2dEffectNode {
    name: RefCell<HSTRING>,
    clsid: GUID,
    properties: Vec<IPropertyValue>,
    source: IGraphicsEffectSource,
}

// IGraphicsEffect inherits IGraphicsEffectSource; implement the marker too.
impl IGraphicsEffectSource_Impl for D2dEffectNode_Impl {}

impl windows::Graphics::Effects::IGraphicsEffect_Impl for D2dEffectNode_Impl {
    fn Name(&self) -> WinResult<HSTRING> {
        Ok(self.name.borrow().clone())
    }

    fn SetName(&self, name: &HSTRING) -> WinResult<()> {
        *self.name.borrow_mut() = name.clone();
        Ok(())
    }
}

impl IGraphicsEffectD2D1Interop_Impl for D2dEffectNode_Impl {
    fn GetEffectId(&self) -> WinResult<GUID> {
        Ok(self.clsid)
    }

    fn GetNamedPropertyMapping(
        &self,
        _name: &PCWSTR,
        _index: *mut u32,
        _mapping: *mut GRAPHICS_EFFECT_PROPERTY_MAPPING,
    ) -> WinResult<()> {
        // Never called: no animatable property declared.
        Err(Error::from(windows::Win32::Foundation::E_NOTIMPL))
    }

    fn GetPropertyCount(&self) -> WinResult<u32> {
        Ok(u32::try_from(self.properties.len()).unwrap_or(u32::MAX))
    }

    fn GetProperty(&self, index: u32) -> WinResult<IPropertyValue> {
        self.properties
            .get(index as usize)
            .cloned()
            .ok_or_else(|| Error::from(windows::Win32::Foundation::E_INVALIDARG))
    }

    fn GetSource(&self, index: u32) -> WinResult<IGraphicsEffectSource> {
        match index {
            0 => Ok(self.source.clone()),
            _ => Err(Error::from(windows::Win32::Foundation::E_INVALIDARG)),
        }
    }

    fn GetSourceCount(&self) -> WinResult<u32> {
        Ok(1)
    }
}

/// Builds a node, returned as `IGraphicsEffect`.
fn node(
    name: &str,
    clsid: GUID,
    properties: Vec<IPropertyValue>,
    source: IGraphicsEffectSource,
) -> IGraphicsEffect {
    D2dEffectNode {
        name: RefCell::new(HSTRING::from(name)),
        clsid,
        properties,
        source,
    }
    .into()
}

/// Casts `IGraphicsEffect` to `IGraphicsEffectSource` for the next node's source.
fn as_source(effect: &IGraphicsEffect) -> Result<IGraphicsEffectSource> {
    effect
        .cast()
        .map_err(map_hr("IGraphicsEffect::cast<IGraphicsEffectSource>"))
}

/// Boxes a FLOAT property.
fn single(v: f32) -> Result<IPropertyValue> {
    PropertyValue::CreateSingle(v)
        .map_err(map_hr("PropertyValue::CreateSingle"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (single)"))
}

/// Boxes a UINT32 (enum) property.
fn uint(v: u32) -> Result<IPropertyValue> {
    PropertyValue::CreateUInt32(v)
        .map_err(map_hr("PropertyValue::CreateUInt32"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (uint)"))
}

/// Boxes a BOOL property.
fn boolean(v: bool) -> Result<IPropertyValue> {
    PropertyValue::CreateBoolean(v)
        .map_err(map_hr("PropertyValue::CreateBoolean"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (boolean)"))
}

/// Creates a `CompositionBrush` that Gaussian-blurs the backdrop and lifts
/// saturation/contrast. `standard_deviation` is logical px (caller does DPI scaling).
///
/// # Errors
/// When effect factory / brush creation fails.
pub fn create_backdrop_blur_brush(
    compositor: &Compositor,
    standard_deviation: f32,
) -> Result<CompositionBrush> {
    let source_param = CompositionEffectSourceParameter::Create(&HSTRING::from(SOURCE_NAME))
        .map_err(map_hr("CompositionEffectSourceParameter::Create"))?;
    let source_param = source_param.cast().map_err(map_hr(
        "CompositionEffectSourceParameter::cast<IGraphicsEffectSource>",
    ))?;

    // GaussianBlur schema: 0 StandardDeviation(FLOAT) / 1 Optimization(enum) /
    // 2 BorderMode(enum).
    let blur_node = node(
        "LineruleBlur",
        CLSID_D2D1GaussianBlur,
        vec![
            single(standard_deviation)?,
            uint(D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED.0 as u32)?,
            uint(D2D1_BORDER_MODE_HARD.0 as u32)?,
        ],
        source_param,
    );

    // Saturation schema: 0 Saturation(FLOAT).
    let saturation_node = node(
        "LineruleSaturation",
        CLSID_D2D1Saturation,
        vec![single(BLUR_SATURATION)?],
        as_source(&blur_node)?,
    );

    // Contrast schema: 0 Contrast(FLOAT) / 1 ClampInput(BOOL).
    let root = node(
        "LineruleContrast",
        CLSID_D2D1Contrast,
        vec![single(BLUR_CONTRAST)?, boolean(false)?],
        as_source(&saturation_node)?,
    );

    let factory = compositor
        .CreateEffectFactory(&root)
        .map_err(map_hr("Compositor::CreateEffectFactory"))?;
    let brush = factory
        .CreateBrush()
        .map_err(map_hr("CompositionEffectFactory::CreateBrush"))?;

    // This transparent WS_EX_NOREDIRECTIONBITMAP overlay must sample the
    // compositor backdrop. HostBackdrop returns black for this window shape.
    let backdrop = compositor
        .CreateBackdropBrush()
        .map_err(map_hr("Compositor::CreateBackdropBrush"))?;
    brush
        .SetSourceParameter(&HSTRING::from(SOURCE_NAME), &backdrop)
        .map_err(map_hr("CompositionEffectBrush::SetSourceParameter"))?;
    brush.cast().map_err(map_hr("CompositionEffectBrush::cast"))
}

const _: GRAPHICS_EFFECT_PROPERTY_MAPPING = GRAPHICS_EFFECT_PROPERTY_MAPPING_DIRECT;
