//! Custom D2D effect-graph description for WinRT Composition.
//!
//! WinRT's only `IGraphicsEffect`-implementing D2D effect classes are in Win2D
//! (UWP-only), so `IGraphicsEffectD2D1Interop` is implemented here as a generic
//! `D2dEffectNode`. Each node holds a CLSID, a property list, and one source;
//! plugging another node into a source builds the effect graph.
//!
//! Backdrop blur builds `backdrop → GaussianBlur(σ) → Saturation → Contrast` and
//! passes the root to `Compositor::CreateEffectFactory`. Plugging a
//! `CompositionBackdropBrush` into the leaf (blur) source yields an effect brush
//! that blurs behind the window and lifts saturation/contrast.

#![allow(
    unsafe_code,
    reason = "FFI boundary; `#[implement]` COM vtable and PropertyValue boxing."
)]
#![allow(
    trivial_casts,
    reason = "from vtable casts generated by the windows-rs `#[implement]` macro."
)]

use std::cell::RefCell;

use windows::Foundation::{IPropertyValue, PropertyValue};
use windows::Graphics::Effects::{
    IGraphicsEffect, IGraphicsEffectSource, IGraphicsEffectSource_Impl,
};
use windows::UI::Composition::{CompositionBrush, CompositionEffectSourceParameter, Compositor};
use windows::Win32::Graphics::Direct2D::Common::D2D1_BORDER_MODE_HARD;
use windows::Win32::Graphics::Direct2D::{
    CLSID_D2D1Contrast, CLSID_D2D1GaussianBlur, CLSID_D2D1Saturation,
    D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED,
};
use windows::Win32::System::WinRT::Graphics::Direct2D::{
    GRAPHICS_EFFECT_PROPERTY_MAPPING, GRAPHICS_EFFECT_PROPERTY_MAPPING_DIRECT,
    IGraphicsEffectD2D1Interop, IGraphicsEffectD2D1Interop_Impl,
};
use windows::core::{Error, GUID, HSTRING, Interface, PCWSTR, Result as WinResult, implement};

use crate::error::{Result, map_hr};

/// Source parameter name passed to CompositionEffectFactory; the same name
/// plugs the backdrop in via `SetSourceParameter`. Only the leaf (GaussianBlur)
/// references it.
const SOURCE_NAME: &str = "source";

/// Default `Saturation` value. `D2D1_SATURATION_PROP_SATURATION` is `[0, 1]`
/// (0.5 = identity, 1.0 = max); above 0.5 raises saturation.
const BLUR_SATURATION: f32 = 0.70;
/// Default `Contrast` value. `D2D1_CONTRAST_PROP_CONTRAST` is `[-1, 1]`
/// (0 = identity); positive increases contrast.
const BLUR_CONTRAST: f32 = 0.15;

/// Generic D2D effect node. Holds one CLSID, a property list (boxed in
/// registered-schema order), and one source (a child node or the backdrop
/// source param), interpreted by CreateEffectFactory as `IGraphicsEffectD2D1Interop`.
///
/// `CreateEffectFactory` validates that property count and types match each
/// CLSID's registered schema and returns `E_INVALIDARG` on mismatch, so
/// properties must be boxed in the right count, order, and type (e.g.
/// `GaussianBlur` 3, `Saturation` 1, `Contrast` 2).
#[implement(IGraphicsEffect, IGraphicsEffectSource, IGraphicsEffectD2D1Interop)]
struct D2dEffectNode {
    name: RefCell<HSTRING>,
    clsid: GUID,
    properties: Vec<IPropertyValue>,
    source: IGraphicsEffectSource,
}

// IGraphicsEffect inherits IGraphicsEffectSource, so implement the marker too.
impl IGraphicsEffectSource_Impl for D2dEffectNode_Impl {}

impl windows::Graphics::Effects::IGraphicsEffect_Impl for D2dEffectNode_Impl {
    fn Name(&self) -> WinResult<HSTRING> {
        Ok(self.name.borrow().clone())
    }

    fn SetName(&self, name: &HSTRING) -> WinResult<()> {
        *self.name.borrow_mut() = name.clone();
        Ok(())
    }
}

impl IGraphicsEffectD2D1Interop_Impl for D2dEffectNode_Impl {
    fn GetEffectId(&self) -> WinResult<GUID> {
        Ok(self.clsid)
    }

    fn GetNamedPropertyMapping(
        &self,
        _name: &PCWSTR,
        _index: *mut u32,
        _mapping: *mut GRAPHICS_EFFECT_PROPERTY_MAPPING,
    ) -> WinResult<()> {
        // Name lookup unimplemented; single-arg CreateEffectFactory declares no
        // animatable property, so this is never called. Return E_NOTIMPL.
        Err(Error::from(windows::Win32::Foundation::E_NOTIMPL))
    }

    fn GetPropertyCount(&self) -> WinResult<u32> {
        // Checked against the registered schema; return the boxed count.
        Ok(u32::try_from(self.properties.len()).unwrap_or(u32::MAX))
    }

    fn GetProperty(&self, index: u32) -> WinResult<IPropertyValue> {
        self.properties
            .get(index as usize)
            .cloned()
            .ok_or_else(|| Error::from(windows::Win32::Foundation::E_INVALIDARG))
    }

    fn GetSource(&self, index: u32) -> WinResult<IGraphicsEffectSource> {
        match index {
            0 => Ok(self.source.clone()),
            _ => Err(Error::from(windows::Win32::Foundation::E_INVALIDARG)),
        }
    }

    fn GetSourceCount(&self) -> WinResult<u32> {
        Ok(1)
    }
}

/// Builds a node and returns it as `IGraphicsEffect` (to feed it into the next
/// source, `.cast::<IGraphicsEffectSource>()`).
fn node(
    name: &str,
    clsid: GUID,
    properties: Vec<IPropertyValue>,
    source: IGraphicsEffectSource,
) -> IGraphicsEffect {
    D2dEffectNode {
        name: RefCell::new(HSTRING::from(name)),
        clsid,
        properties,
        source,
    }
    .into()
}

/// Casts `IGraphicsEffect` to `IGraphicsEffectSource` for use as the next node's
/// source.
fn as_source(effect: &IGraphicsEffect) -> Result<IGraphicsEffectSource> {
    effect
        .cast()
        .map_err(map_hr("IGraphicsEffect::cast<IGraphicsEffectSource>"))
}

/// Boxes a FLOAT property.
fn single(v: f32) -> Result<IPropertyValue> {
    PropertyValue::CreateSingle(v)
        .map_err(map_hr("PropertyValue::CreateSingle"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (single)"))
}

/// Boxes a UINT32 (enum) property.
fn uint(v: u32) -> Result<IPropertyValue> {
    PropertyValue::CreateUInt32(v)
        .map_err(map_hr("PropertyValue::CreateUInt32"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (uint)"))
}

/// Boxes a BOOL property (D2D `D2D1_PROPERTY_TYPE_BOOL`; Boolean, as in Win2D).
fn boolean(v: bool) -> Result<IPropertyValue> {
    PropertyValue::CreateBoolean(v)
        .map_err(map_hr("PropertyValue::CreateBoolean"))?
        .cast()
        .map_err(map_hr("PropertyValue::cast (boolean)"))
}

/// Reads an f32 from env; invalid values fall back to `default`.
fn env_f32(name: &str, default: f32) -> f32 {
    std::env::var(name)
        .ok()
        .and_then(|s| s.trim().parse::<f32>().ok())
        .filter(|v| v.is_finite())
        .unwrap_or(default)
}

/// Blur post-process tuning, parsed once from env (so the knobs are read at
/// renderer construction, not on every brush rebuild).
#[derive(Clone, Copy)]
pub struct BlurConfig {
    /// Saturation effect value, `[0, 1]` (0.5 = identity).
    saturation: f32,
    /// Contrast effect value, `[-1, 1]` (0 = identity).
    contrast: f32,
    /// Use `CreateHostBackdropBrush` instead of `CreateBackdropBrush`.
    host_backdrop: bool,
}

impl BlurConfig {
    /// Parse the `LINERULE_BLUR_*` env knobs, clamped to valid ranges.
    #[must_use]
    pub fn from_env() -> Self {
        Self {
            saturation: env_f32("LINERULE_BLUR_SATURATION", BLUR_SATURATION).clamp(0.0, 1.0),
            contrast: env_f32("LINERULE_BLUR_CONTRAST", BLUR_CONTRAST).clamp(-1.0, 1.0),
            host_backdrop: std::env::var("LINERULE_BLUR_HOST").is_ok(),
        }
    }
}

/// Creates a `CompositionBrush` that Gaussian-blurs the backdrop and then lifts
/// saturation/contrast. `standard_deviation` is in logical px (DPI scaling done
/// by the caller). Saturation, contrast, and backdrop kind come from `blur`
/// (`BlurConfig`, parsed once from env at startup).
///
/// # Errors
/// When effect factory / brush creation fails.
pub fn create_backdrop_blur_brush(
    compositor: &Compositor,
    standard_deviation: f32,
    blur: &BlurConfig,
) -> Result<CompositionBrush> {
    let source_param = CompositionEffectSourceParameter::Create(&HSTRING::from(SOURCE_NAME))
        .map_err(map_hr("CompositionEffectSourceParameter::Create"))?;
    let source_param = source_param.cast().map_err(map_hr(
        "CompositionEffectSourceParameter::cast<IGraphicsEffectSource>",
    ))?;

    // backdrop → GaussianBlur → Saturation → Contrast.
    // GaussianBlur properties: 0 StandardDeviation(FLOAT) / 1 Optimization(enum) /
    // 2 BorderMode(enum) — 3 total (count/type must match schema or E_INVALIDARG).
    let blur_node = node(
        "LineruleBlur",
        CLSID_D2D1GaussianBlur,
        vec![
            single(standard_deviation)?,
            uint(D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED.0 as u32)?,
            uint(D2D1_BORDER_MODE_HARD.0 as u32)?,
        ],
        source_param,
    );

    // Saturation properties: 0 Saturation(FLOAT) — 1 total.
    let saturation_node = node(
        "LineruleSaturation",
        CLSID_D2D1Saturation,
        vec![single(blur.saturation)?],
        as_source(&blur_node)?,
    );

    // Contrast properties: 0 Contrast(FLOAT) / 1 ClampInput(BOOL) — 2 total.
    let root = node(
        "LineruleContrast",
        CLSID_D2D1Contrast,
        vec![single(blur.contrast)?, boolean(false)?],
        as_source(&saturation_node)?,
    );

    let factory = compositor
        .CreateEffectFactory(&root)
        .map_err(map_hr("Compositor::CreateEffectFactory"))?;
    let brush = factory
        .CreateBrush()
        .map_err(map_hr("CompositionEffectFactory::CreateBrush"))?;

    // Backdrop selection. For this transparent (WS_EX_NOREDIRECTIONBITMAP)
    // overlay, `CreateBackdropBrush` samples behind the window (other apps /
    // desktop), since there is no redirection surface. `CreateHostBackdropBrush`
    // returns black for such windows. `LINERULE_BLUR_HOST=1` switches to host
    // backdrop for comparison.
    let backdrop = if blur.host_backdrop {
        compositor
            .CreateHostBackdropBrush()
            .map_err(map_hr("Compositor::CreateHostBackdropBrush"))?
    } else {
        compositor
            .CreateBackdropBrush()
            .map_err(map_hr("Compositor::CreateBackdropBrush"))?
    };
    brush
        .SetSourceParameter(&HSTRING::from(SOURCE_NAME), &backdrop)
        .map_err(map_hr("CompositionEffectBrush::SetSourceParameter"))?;
    brush.cast().map_err(map_hr("CompositionEffectBrush::cast"))
}

const _: GRAPHICS_EFFECT_PROPERTY_MAPPING = GRAPHICS_EFFECT_PROPERTY_MAPPING_DIRECT;
